services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./database/migrations:/var/www/html/database/migrations # Store SQLite data in a persistent volume
        # Run migrations as part of the startup command, then start PHP-FPM
        command: sh -c "php artisan migrate --force && php-fpm"
        expose:
            - "9000"  # Expose PHP-FPM on port 9000 for nginx to access

    webserver:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - app  # nginx depends on the PHP app for processing requests

volumes:
    db_data:
